version: "3.9"

services:

    db:
      image: postgres:13.3
      environment:
        - POSTGRES_PASSWORD=postgres
      ports:
        - "127.0.0.1:5432:5432"

    redis:
      image: redis:6
      ports:
        - "127.0.0.1:6379:6379"

    api:
      build: .
      entrypoint: /home/user/app/entrypoint.sh
      working_dir: /home/user/app/src
      volumes:
        - .:/home/user/app
      ports:
        - "127.0.0.1:8000:8000"
      env_file: .env
      depends_on:
        - db
        - redis
