[tool.poetry]
name = "symfall"
version = "0.10.1"
description = "add poetry"
authors = ["swaroggot"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.1"
djangorestframework = "^3.12.1"
psycopg2-binary = "^2.8.6"
django_extended_choices = "^1.3.3"
pendulum = "^2.1.2"
coo = "^0.1.3"
sentry_sdk = "^0.17.8"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
