[tool.poetry]
name = "Symfall"
version = "0.11.0"
description = "Simple messenger to improve self skills"
authors = ["swaroggot", "valeriiduz"]

[tool.poetry.dependencies]
python = "^3.8"
djangorestframework = "3.12.1"
psycopg2-binary = "2.8.6"
django_extended_choices = "1.3.3"
sentry_sdk = "0.17.8"
appdirs = "1.4.4"
drf-yasg = "1.20.0"
celery = "5.0.0"
redis = "3.5.3"
psutil = "5.7.2"
django-extensions = "3.1.0"
Django = "3.1.6"
django-health-check = "3.16.2"
django-storages = "1.11.1"
google-cloud-storage = "1.36.0"
Faker = "6.3.0"
Pillow = "^8.1.0"
channels = "^3.0.3"
channels-redis = "^3.2.0"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
freezegun = "1.1.0"
prospector = "1.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
