# Generated by Django 3.2.5 on 2021-08-18 20:51

from django.db import migrations

import messenger.fields


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="document",
            field=messenger.fields.ContentTypeRestrictedFileField(
                upload_to="file/"
            ),
        ),
    ]
