version: "3.9"

services:
    db:
      image: postgres:13
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    redis:
      image: redis:6
    api:
      image: symfall/api:latest
      entrypoint: /code/entrypoint.sh
      ports:
        - "80:8000"
      depends_on:
        - db
        - redis
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - DEBUG=${DEBUG}
        - SENTRY_DSN=${SENTRY_DSN}
