version: "3"

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mailo1998
    redis:
      image: "redis:alpine"
    api:
      build: ""
      entrypoint: ./entrypoint.sh
      ports:
        - "80:8000"
      env_file: .env
      depends_on:
        - db
        - redis
