version: "3.9"

services:

    db:
      image: postgres:13
      environment:
        - POSTGRES_PASSWORD=postgres

    redis:
      image: redis:6

    api:
      build: ..
      volumes:
        - ../:/code
      working_dir: /code/src
      depends_on:
        - db
        - redis
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - DEBUG=${DEBUG}
        - ENVIROMENT=test
