version: '3'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mailo1998
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      env_file:
        - ./.env.dev
<<<<<<< HEAD
        - ./.env.dist
=======
>>>>>>> 7dcb38a4606909668786f55b3436f29af47c2bce
      depends_on:
        - db
