[tool.poetry]
name = "messenger"
version = "0.1.0"
description = "add poetry"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.8.2"
django = "^3.1.1"
psycopg2-binary = "^2.8.6"
djangorestframework = "^3.11.1"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
